#!/bin/sh
if tos3to4-automatic; then
	create_notification -s news \
"Váš router bude automaticky aktualizován na nejnovější verzi Turris OS. Další aktualizace nainstaluje balíček 'tos3to4' a migrace započne.

Více informací naleznete v dokumentaci https://docs.turris.cz/geek/tos3-migration/." \
"The automatic migration to the latest Turris OS version was enabled for your router. The next update is going to install package 'tos3to4' and initiate the migration.

More info is available in the official documentation https://docs.turris.cz/geek/tos3-migration/."
else
	create_notification -s news \
"Podpora verze Turris OS 3.x byla ukončena k 7.1.2022. Tato verze již nedostává bezpečnostní aktualizace a důrazně doporučujeme aktualizaci na nejnovější verzi Turris OS.

Aktualizace na nejnovější verzi Turris OS je k dispozici. Pro provedení je nutný ruční zásah. Důrazně doporučujeme toto udělat co nejdříve, protože migrace nebude oficiálně podporována od vydání Turris OS verze 6.0.0.

Prosím přečtěte si instrukce v dokumentaci https://docs.turris.cz/geek/tos3-migration/." \
"The Turris OS 3.x support was terminated since 7.1.2022. This version no longer receives security updates and we highly recommend update to the latest Turris OS version.

Update to the latest Turris OS version is available. The update requires manual intervention. It is highly recommended to trigger update as soon as possible because migration process won't be supported after Turris OS 6.0.0 release.

Please read the instruction in the official documentation https://docs.turris.cz/geek/tos3-migration/."
fi
