#!/bin/sh
set -e
. /lib/functions/sentinel-firewall.sh

# Remove old rules
uci -q delete firewall.sentinel_dynfw_client || :
uci -q delete firewall.sentinel_dynfw_client_ipset || :

# Always reload firewall to use latest version of sentinel-firewall script
/etc/init.d/firewall reload
