#!/bin/sh /etc/rc.common
START=01
STOP=01

boot() {
    /usr/libexec/minirainbow/set_brightness.sh
    echo 255 255 0 > /sys/class/leds/rgb:power/multi_intensity
    echo heartbeat > /sys/class/leds/rgb:power/trigger
}

restart() { :; }

stop() {
    /usr/libexec/minirainbow/set_brightness.sh
    echo 255 255 0 > /sys/class/leds/rgb:power/multi_intensity
    echo heartbeat > /sys/class/leds/rgb:power/trigger
}
