## API CGI
$HTTP["url"] =~ "^/repakon/api" {
    cgi.assign += ( "" => "" )
}

# Set security
$HTTP["url"] =~ "^/repakon/" {
    fastcgi.server = ( "/" => ( turris_auth_scriptname => turris_auth ))
}

## Set URLs
alias.url += (
    "/repakon/api" => "/www/cgi-bin/repakon",
    "/repakon/" => "/www/repakon/"
)
$HTTP["url"] =~ "^/repakon$" {
    url.redirect = ( "^/repakon$" => "/repakon/" )
}
