#!/bin/sh
if [ -z "${IPKG_INSTROOT}" ]; then
    fstype=$(sed -nr 's/.*rootfstype=([a-z0-9]+).*/\1/p' /proc/cmdline)
    case $fstype in
    "jffs2")
    	echo "JFFS2 rootfstype found"
	echo "Erasing and flashing FDT partition."
	flash_erase /dev/mtd6 0 0 && nandwrite -p /dev/mtd6 /boot/fdt-hw-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1

	echo "Erasing and flashing kernel partition."
	if [ -f /lib/uboot/uboot-1.installed ]; then
		( flash_erase /dev/mtd7 0 0 && nandwrite -p /dev/mtd7 /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 && head -c `wc -c /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 | sed 's| .*||'` > /tmp/zimage-check && cmp /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 /tmp/zimage-check ) || ( mtd erase /dev/mtd7 && mtd write /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 /dev/mtd7 && head -c `wc -c /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 | sed 's| .*||'` > /tmp/zimage-check && cmp /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 /tmp/zimage-check )
	else
		echo "[ -f /lib/uboot/uboot-1.installed ] && \\" > /etc/uci-defaults/11-flash_kernel
		echo "flash_erase /dev/mtd7 0 0 && nandwrite -p /dev/mtd7 /boot/zImage-4.4.199-1-f90a52a6230ecb072f657fce5aebd444-1 && \\" >> /etc/uci-defaults/11-flash_kernel
		echo "reboot" >> /etc/uci-defaults/11-flash_kernel
	fi
	;;
    "ubifs")
    	echo "UBIFS rootfstype found"
        ;;
    esac
fi
