#!/bin/sh
set -x

[ "$ACTION" = "pressed" ] || exit 0

/usr/libexec/minirainbow/state_update.sh

DIM_STATE=$(uci get rainbow.state.dim)
DIM_STATE=$((DIM_STATE+1))


[ "$DIM_STATE" -ge 8 ] && DIM_STATE=0

uci set rainbow.state.dim=$DIM_STATE
uci commit rainbow


if [ "$DIM_STATE" = 0 ]; then
	# reset triggers (calls set_brightness.sh)
	/etc/init.d/led restart
	/usr/libexec/minirainbow.sh --oneshot &
else
	/usr/libexec/minirainbow/set_brightness.sh
fi

