#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	source /etc/profile.d/peacomp-wayland-display.sh
	mkdir -p "$XDG_RUNTIME_DIR"
	chown $USER "$XDG_RUNTIME_DIR"
	chmod 0700 "$XDG_RUNTIME_DIR"
	procd_open_instance
	procd_set_param command "/usr/bin/peacomp"
	procd_set_param stdout  1
	procd_set_param stderr  1
	procd_set_param env PEACOMP_BACKEND=linux XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" PEACOMP_WAYLAND_DISPLAY="path:${WAYLAND_DISPLAY}"
	procd_close_instance
}
