#!/bin/sh

# Add LEDs to board.json
(CFG=/etc/board.json . /etc/board.d/01_leds)

# Regenerate LED config if not user-modified
if ! grep -q 'config led' /etc/config/system; then
	mv /etc/config/system /etc/config/system.bak
	config_generate
	cat /etc/config/system | sed -n '/config led/,$p' >> /etc/config/system.bak
	mv /etc/config/system.bak /etc/config/system
	/etc/init.d/led restart
fi

# Remove old config
rm -f /etc/config/rainbow
